#pragma once

//C = const
//V = variable
//I = intermediate

#define _KSN_MATH_FORMULA_INSTRUCTION_ADD_CV				0x00
#define _KSN_MATH_FORMULA_INSTRUCTION_ADD_CI				0x01
#define _KSN_MATH_FORMULA_INSTRUCTION_ADD_VC				0x02
#define _KSN_MATH_FORMULA_INSTRUCTION_ADD_VV				0x03
#define _KSN_MATH_FORMULA_INSTRUCTION_ADD_VI				0x04
#define _KSN_MATH_FORMULA_INSTRUCTION_ADD_IC				0x05
#define _KSN_MATH_FORMULA_INSTRUCTION_ADD_IV				0x06
#define _KSN_MATH_FORMULA_INSTRUCTION_ADD_II				0x07

#define _KSN_MATH_FORMULA_INSTRUCTION_SUB_CV				0x08
#define _KSN_MATH_FORMULA_INSTRUCTION_SUB_CI				0x09
#define _KSN_MATH_FORMULA_INSTRUCTION_SUB_VC				0x0A
#define _KSN_MATH_FORMULA_INSTRUCTION_SUB_VV				0x0B
#define _KSN_MATH_FORMULA_INSTRUCTION_SUB_VI				0x0C
#define _KSN_MATH_FORMULA_INSTRUCTION_SUB_IC				0x0D
#define _KSN_MATH_FORMULA_INSTRUCTION_SUB_IV				0x0E
#define _KSN_MATH_FORMULA_INSTRUCTION_SUB_II					0x0F

#define _KSN_MATH_FORMULA_INSTRUCTION_MUL_CV				0x10
#define _KSN_MATH_FORMULA_INSTRUCTION_MUL_CI				0x11
#define _KSN_MATH_FORMULA_INSTRUCTION_MUL_VC				0x12
#define _KSN_MATH_FORMULA_INSTRUCTION_MUL_VV				0x13
#define _KSN_MATH_FORMULA_INSTRUCTION_MUL_VI				0x14
#define _KSN_MATH_FORMULA_INSTRUCTION_MUL_IC				0x15
#define _KSN_MATH_FORMULA_INSTRUCTION_MUL_IV				0x16
#define _KSN_MATH_FORMULA_INSTRUCTION_MUL_II					0x17

#define _KSN_MATH_FORMULA_INSTRUCTION_DIV_CV				0x18
#define _KSN_MATH_FORMULA_INSTRUCTION_DIV_CI					0x19
#define _KSN_MATH_FORMULA_INSTRUCTION_DIV_VC				0x1A
#define _KSN_MATH_FORMULA_INSTRUCTION_DIV_VV				0x1B
#define _KSN_MATH_FORMULA_INSTRUCTION_DIV_VI					0x1C
#define _KSN_MATH_FORMULA_INSTRUCTION_DIV_IC					0x1D
#define _KSN_MATH_FORMULA_INSTRUCTION_DIV_IV					0x1E
#define _KSN_MATH_FORMULA_INSTRUCTION_DIV_II					0x1F

#define _KSN_MATH_FORMULA_INSTRUCTION_POW_CV				0x20
#define _KSN_MATH_FORMULA_INSTRUCTION_POW_CI				0x21
#define _KSN_MATH_FORMULA_INSTRUCTION_POW_VC				0x22
#define _KSN_MATH_FORMULA_INSTRUCTION_POW_VV				0x23
#define _KSN_MATH_FORMULA_INSTRUCTION_POW_VI				0x24
#define _KSN_MATH_FORMULA_INSTRUCTION_POW_IC				0x25
#define _KSN_MATH_FORMULA_INSTRUCTION_POW_IV				0x26
#define _KSN_MATH_FORMULA_INSTRUCTION_POW_II				0x27

#define _KSN_MATH_FORMULA_INSTRUCTION_IDIV_CV				0x28
#define _KSN_MATH_FORMULA_INSTRUCTION_IDIV_CI				0x29
#define _KSN_MATH_FORMULA_INSTRUCTION_IDIV_VC				0x2A
#define _KSN_MATH_FORMULA_INSTRUCTION_IDIV_VV				0x2B
#define _KSN_MATH_FORMULA_INSTRUCTION_IDIV_VI				0x2C
#define _KSN_MATH_FORMULA_INSTRUCTION_IDIV_IC				0x2D
#define _KSN_MATH_FORMULA_INSTRUCTION_IDIV_IV				0x2E
#define _KSN_MATH_FORMULA_INSTRUCTION_IDIV_II				0x2F

#define _KSN_MATH_FORMULA_INSTRUCTION_MOD_CV				0x30
#define _KSN_MATH_FORMULA_INSTRUCTION_MOD_CI				0x31
#define _KSN_MATH_FORMULA_INSTRUCTION_MOD_VC				0x32
#define _KSN_MATH_FORMULA_INSTRUCTION_MOD_VV				0x33
#define _KSN_MATH_FORMULA_INSTRUCTION_MOD_VI				0x34
#define _KSN_MATH_FORMULA_INSTRUCTION_MOD_IC				0x35
#define _KSN_MATH_FORMULA_INSTRUCTION_MOD_IV				0x36
#define _KSN_MATH_FORMULA_INSTRUCTION_MOD_II				0x37

#define _KSN_MATH_FORMULA_INSTRUCTION_RET_C					0xFB
#define _KSN_MATH_FORMULA_INSTRUCTION_RET_V					0xFC
#define _KSN_MATH_FORMULA_INSTRUCTION_RET_I					0xFD

#define _KSN_MATH_FORMULA_EXTENDED_INSTRUCTION			0xFE

#define _KSN_MATH_FORMULA_INVALID_INSTRUCTION				0xFF
